Regenerated

diff --git a/guile/guile-oops/configure b/guile/guile-oops/configure
--- a/guile/guile-oops/configure
+++ b/guile/guile-oops/configure
@@ -836,8 +836,8 @@ echo "configure:829: checking for Guile" >&5
   
   echo "$ac_t""yes" 1>&6
 
-if test "`guile -c '(display (string>=? (version) "1.3.2"))'`" != "#t"; then
-  { echo "configure: error: Your Guile is too old.  You need guile-core-1.3.2 or later." 1>&2; exit 1; }
+if test "`guile -c '(display (string>=? (version) "1.3.3"))'`" != "#t"; then
+  { echo "configure: error: Your Guile is too old.  You need guile-core-1.3.3 or later." 1>&2; exit 1; }
 fi
 
 # Extract the first word of "gcc", so it can be a program name with args.
@@ -1516,62 +1516,6 @@ exec 5>>./config.log
 
 CFLAGS="$CFLAGS $GUILE_CFLAGS"
 LIBS="$LIBS $GUILE_LDFLAGS"
-
-for ac_func in scm_apply_generic
-do
-echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:1524: checking for $ac_func" >&5
-if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  cat > conftest.$ac_ext <<EOF
-#line 1529 "configure"
-#include "confdefs.h"
-/* System header to define __stub macros and hopefully few prototypes,
-    which can conflict with char $ac_func(); below.  */
-#include <assert.h>
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char $ac_func();
-
-int main() {
-
-/* The GNU C library defines this for functions which it implements
-    to always fail with ENOSYS.  Some functions are actually named
-    something starting with __ and the normal name is an alias.  */
-#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
-choke me
-#else
-$ac_func();
-#endif
-
-; return 0; }
-EOF
-if { (eval echo configure:1552: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  eval "ac_cv_func_$ac_func=yes"
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_func_$ac_func=no"
-fi
-rm -f conftest*
-fi
-
-if eval "test \"`echo '$ac_cv_func_'$ac_func`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-    ac_tr_func=HAVE_`echo $ac_func | tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'`
-  cat >> confdefs.h <<EOF
-#define $ac_tr_func 1
-EOF
- 
-else
-  echo "$ac_t""no" 1>&6
-fi
-done
-
 
 ## If we're using GCC, ask for aggressive warnings.
 case "$GCC" in
